<?php

/**
 * BaseRegistro_Estado_Tarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idRegistroTarea
 * @property integer $statusFK
 * @property integer $tareaFK
 * @property Status $Status
 * @property Tarea $Tarea
 * 
 * @method integer               getIdRegistroTarea() Returns the current record's "idRegistroTarea" value
 * @method integer               getStatusFK()        Returns the current record's "statusFK" value
 * @method integer               getTareaFK()         Returns the current record's "tareaFK" value
 * @method Status                getStatus()          Returns the current record's "Status" value
 * @method Tarea                 getTarea()           Returns the current record's "Tarea" value
 * @method Registro_Estado_Tarea setIdRegistroTarea() Sets the current record's "idRegistroTarea" value
 * @method Registro_Estado_Tarea setStatusFK()        Sets the current record's "statusFK" value
 * @method Registro_Estado_Tarea setTareaFK()         Sets the current record's "tareaFK" value
 * @method Registro_Estado_Tarea setStatus()          Sets the current record's "Status" value
 * @method Registro_Estado_Tarea setTarea()           Sets the current record's "Tarea" value
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistro_Estado_Tarea extends sfMapFishRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registro__estado__tarea');
        $this->hasColumn('idRegistroTarea', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('statusFK', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tareaFK', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Status', array(
             'local' => 'statusFK',
             'foreign' => 'idStatus',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Tarea', array(
             'local' => 'tareaFK',
             'foreign' => 'idTarea',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'fecha_cambio_estado',
              'type' => 'timestamp',
             ),
             ));
        $this->actAs($timestampable0);
    }
}