<?php

/**
 * BaseTarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idTarea
 * @property string $nombreTarea
 * @property integer $duracion
 * @property integer $statusFK
 * @property integer $prioridadFK
 * @property integer $proyectoFK
 * @property Status $Status
 * @property Prioridad $Prioridad
 * @property Proyecto $Proyecto
 * @property Doctrine_Collection $Usuario
 * @property Doctrine_Collection $RegistroEstados
 * 
 * @method integer             getIdTarea()         Returns the current record's "idTarea" value
 * @method string              getNombreTarea()     Returns the current record's "nombreTarea" value
 * @method integer             getDuracion()        Returns the current record's "duracion" value
 * @method integer             getStatusFK()        Returns the current record's "statusFK" value
 * @method integer             getPrioridadFK()     Returns the current record's "prioridadFK" value
 * @method integer             getProyectoFK()      Returns the current record's "proyectoFK" value
 * @method Status              getStatus()          Returns the current record's "Status" value
 * @method Prioridad           getPrioridad()       Returns the current record's "Prioridad" value
 * @method Proyecto            getProyecto()        Returns the current record's "Proyecto" value
 * @method Doctrine_Collection getUsuario()         Returns the current record's "Usuario" collection
 * @method Doctrine_Collection getRegistroEstados() Returns the current record's "RegistroEstados" collection
 * @method Tarea               setIdTarea()         Sets the current record's "idTarea" value
 * @method Tarea               setNombreTarea()     Sets the current record's "nombreTarea" value
 * @method Tarea               setDuracion()        Sets the current record's "duracion" value
 * @method Tarea               setStatusFK()        Sets the current record's "statusFK" value
 * @method Tarea               setPrioridadFK()     Sets the current record's "prioridadFK" value
 * @method Tarea               setProyectoFK()      Sets the current record's "proyectoFK" value
 * @method Tarea               setStatus()          Sets the current record's "Status" value
 * @method Tarea               setPrioridad()       Sets the current record's "Prioridad" value
 * @method Tarea               setProyecto()        Sets the current record's "Proyecto" value
 * @method Tarea               setUsuario()         Sets the current record's "Usuario" collection
 * @method Tarea               setRegistroEstados() Sets the current record's "RegistroEstados" collection
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTarea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tarea');
        $this->hasColumn('idTarea', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombreTarea', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('duracion', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('statusFK', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('prioridadFK', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('proyectoFK', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Status', array(
             'local' => 'statusFK',
             'foreign' => 'idStatus',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Prioridad', array(
             'local' => 'prioridadFK',
             'foreign' => 'idPrioridad',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Proyecto', array(
             'local' => 'proyectoFK',
             'foreign' => 'idProyecto',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Usuario', array(
             'refClass' => 'UsuarioTarea',
             'local' => 'idTarea',
             'foreign' => 'idUsuario'));

        $this->hasMany('Registro_Estado_Tarea as RegistroEstados', array(
             'local' => 'idTarea',
             'foreign' => 'tareaFK'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'tar_fecha_creacion',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'name' => 'tar_fecha_actulizacion',
              'type' => 'timestamp',
             ),
             ));
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($timestampable0);
        $this->actAs($nestedset0);
    }
}