<?php

/**
 * BaseUsuarioTarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idUsuario
 * @property integer $idTarea
 * 
 * @method integer      getIdUsuario() Returns the current record's "idUsuario" value
 * @method integer      getIdTarea()   Returns the current record's "idTarea" value
 * @method UsuarioTarea setIdUsuario() Sets the current record's "idUsuario" value
 * @method UsuarioTarea setIdTarea()   Sets the current record's "idTarea" value
 * @property  $
 * @property  $
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuarioTarea extends sfMapFishRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario_tarea');
        $this->hasColumn('idUsuario', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('idTarea', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('usuario', array(
             'local' => 'idUsuario',
             'foreign' => 'idUsuario',
             'onDelete' => 'CASCADE'));

        $this->hasOne('tarea', array(
             'local' => 'idTarea',
             'foreign' => 'idTarea',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'fecha_asignacion',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'name' => 'fecha_actualizacion',
              'type' => 'timestamp',
             ),
             ));
        $this->actAs($timestampable0);
    }
}