<?php

/**
 * BaseTipo_usuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idTipoUsuario
 * @property string $tipo_nombre
 * @property Doctrine_Collection $Usuarios
 * 
 * @method integer             getIdTipoUsuario() Returns the current record's "idTipoUsuario" value
 * @method string              getTipoNombre()    Returns the current record's "tipo_nombre" value
 * @method Doctrine_Collection getUsuarios()      Returns the current record's "Usuarios" collection
 * @method Tipo_usuario        setIdTipoUsuario() Sets the current record's "idTipoUsuario" value
 * @method Tipo_usuario        setTipoNombre()    Sets the current record's "tipo_nombre" value
 * @method Tipo_usuario        setUsuarios()      Sets the current record's "Usuarios" collection
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipo_usuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_usuario');
        $this->hasColumn('idTipoUsuario', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('tipo_nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Usuario as Usuarios', array(
             'local' => 'idTipoUsuario',
             'foreign' => 'tipoUsuarioPK'));
    }
}