<?php

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idUsuario
 * @property integer $tipo_idTipoUsuario
 * @property string $usr_nombre
 * @property string $usr_apellido1
 * @property string $usr_apellido2
 * @property string $email
 * @property string $usr_nick
 * @property string $password
 * @property Tipo_usuario $Tipo_usuario
 * @property Doctrine_Collection $Usuario_Tarea
 * @property Doctrine_Collection $Grupo_Usuario
 * 
 * @method integer             getIdUsuario()          Returns the current record's "idUsuario" value
 * @method integer             getTipoIdTipoUsuario()  Returns the current record's "tipo_idTipoUsuario" value
 * @method string              getUsrNombre()          Returns the current record's "usr_nombre" value
 * @method string              getUsrApellido1()       Returns the current record's "usr_apellido1" value
 * @method string              getUsrApellido2()       Returns the current record's "usr_apellido2" value
 * @method string              getEmail()              Returns the current record's "email" value
 * @method string              getUsrNick()            Returns the current record's "usr_nick" value
 * @method string              getPassword()           Returns the current record's "password" value
 * @method Tipo_usuario        getTipoUsuario()        Returns the current record's "Tipo_usuario" value
 * @method Doctrine_Collection getUsuarioTarea()       Returns the current record's "Usuario_Tarea" collection
 * @method Doctrine_Collection getGrupoUsuario()       Returns the current record's "Grupo_Usuario" collection
 * @method Usuario             setIdUsuario()          Sets the current record's "idUsuario" value
 * @method Usuario             setTipoIdTipoUsuario()  Sets the current record's "tipo_idTipoUsuario" value
 * @method Usuario             setUsrNombre()          Sets the current record's "usr_nombre" value
 * @method Usuario             setUsrApellido1()       Sets the current record's "usr_apellido1" value
 * @method Usuario             setUsrApellido2()       Sets the current record's "usr_apellido2" value
 * @method Usuario             setEmail()              Sets the current record's "email" value
 * @method Usuario             setUsrNick()            Sets the current record's "usr_nick" value
 * @method Usuario             setPassword()           Sets the current record's "password" value
 * @method Usuario             setTipoUsuario()        Sets the current record's "Tipo_usuario" value
 * @method Usuario             setUsuarioTarea()       Sets the current record's "Usuario_Tarea" collection
 * @method Usuario             setGrupoUsuario()       Sets the current record's "Grupo_Usuario" collection
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('idUsuario', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('tipo_idTipoUsuario', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('usr_nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('usr_apellido1', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('usr_apellido2', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('usr_nick', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 20,
             ));
        $this->hasColumn('password', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tipo_usuario', array(
             'local' => 'tipo_idTipoUsuario',
             'foreign' => 'idTipoUsuario',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Usuario_Tarea', array(
             'local' => 'idUsuario',
             'foreign' => 'usuario_id'));

        $this->hasMany('Grupo_Usuario', array(
             'local' => 'idUsuario',
             'foreign' => 'usuario_idUsuario'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}