<?php

/**
 * BaseRegistro_Estado_Proyecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $fecha_cambio_estado
 * @property integer $status_idStatus
 * @property integer $proyecto_idProyecto
 * @property Status $Status
 * @property Proyecto $Proyecto
 * 
 * @method timestamp                getFechaCambioEstado()   Returns the current record's "fecha_cambio_estado" value
 * @method integer                  getStatusIdStatus()      Returns the current record's "status_idStatus" value
 * @method integer                  getProyectoIdProyecto()  Returns the current record's "proyecto_idProyecto" value
 * @method Status                   getStatus()              Returns the current record's "Status" value
 * @method Proyecto                 getProyecto()            Returns the current record's "Proyecto" value
 * @method Registro_Estado_Proyecto setFechaCambioEstado()   Sets the current record's "fecha_cambio_estado" value
 * @method Registro_Estado_Proyecto setStatusIdStatus()      Sets the current record's "status_idStatus" value
 * @method Registro_Estado_Proyecto setProyectoIdProyecto()  Sets the current record's "proyecto_idProyecto" value
 * @method Registro_Estado_Proyecto setStatus()              Sets the current record's "Status" value
 * @method Registro_Estado_Proyecto setProyecto()            Sets the current record's "Proyecto" value
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistro_Estado_Proyecto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registro__estado__proyecto');
        $this->hasColumn('fecha_cambio_estado', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('status_idStatus', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('proyecto_idProyecto', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Status', array(
             'local' => 'status_idStatus',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Proyecto', array(
             'local' => 'proyecto_idProyecto',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}