<?php

/**
 * BaseEvento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idEvento
 * @property timestamp $fechaEvento
 * @property string $nombreEvento
 * @property string $descEvento
 * @property integer $proyecto_idProyecto
 * @property Proyecto $Proyecto
 * 
 * @method integer   getIdEvento()            Returns the current record's "idEvento" value
 * @method timestamp getFechaEvento()         Returns the current record's "fechaEvento" value
 * @method string    getNombreEvento()        Returns the current record's "nombreEvento" value
 * @method string    getDescEvento()          Returns the current record's "descEvento" value
 * @method integer   getProyectoIdProyecto()  Returns the current record's "proyecto_idProyecto" value
 * @method Proyecto  getProyecto()            Returns the current record's "Proyecto" value
 * @method Evento    setIdEvento()            Sets the current record's "idEvento" value
 * @method Evento    setFechaEvento()         Sets the current record's "fechaEvento" value
 * @method Evento    setNombreEvento()        Sets the current record's "nombreEvento" value
 * @method Evento    setDescEvento()          Sets the current record's "descEvento" value
 * @method Evento    setProyectoIdProyecto()  Sets the current record's "proyecto_idProyecto" value
 * @method Evento    setProyecto()            Sets the current record's "Proyecto" value
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evento');
        $this->hasColumn('idEvento', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('fechaEvento', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('nombreEvento', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('descEvento', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('proyecto_idProyecto', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proyecto', array(
             'local' => 'proyecto_idProyecto',
             'foreign' => 'idProyecto',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}