<?php

/**
 * BaseGrupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombreGrupo
 * @property string $descGrupo
 * @property Doctrine_Collection $Tareas
 * 
 * @method string              getNombreGrupo() Returns the current record's "nombreGrupo" value
 * @method string              getDescGrupo()   Returns the current record's "descGrupo" value
 * @method Doctrine_Collection getTareas()      Returns the current record's "Tareas" collection
 * @method Grupo               setNombreGrupo() Sets the current record's "nombreGrupo" value
 * @method Grupo               setDescGrupo()   Sets the current record's "descGrupo" value
 * @method Grupo               setTareas()      Sets the current record's "Tareas" collection
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrupo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grupo');
        $this->hasColumn('nombreGrupo', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('descGrupo', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tarea as Tareas', array(
             'local' => 'id',
             'foreign' => 'idGrupo'));
    }
}