<?php

/**
 * BaseGrupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idGrupo
 * @property string $nombreGrupo
 * @property string $descGrupo
 * @property Doctrine_Collection $Tareas
 * @property Doctrine_Collection $Grupo_Usuario
 * 
 * @method integer             getIdGrupo()       Returns the current record's "idGrupo" value
 * @method string              getNombreGrupo()   Returns the current record's "nombreGrupo" value
 * @method string              getDescGrupo()     Returns the current record's "descGrupo" value
 * @method Doctrine_Collection getTareas()        Returns the current record's "Tareas" collection
 * @method Doctrine_Collection getGrupoUsuario()  Returns the current record's "Grupo_Usuario" collection
 * @method Grupo               setIdGrupo()       Sets the current record's "idGrupo" value
 * @method Grupo               setNombreGrupo()   Sets the current record's "nombreGrupo" value
 * @method Grupo               setDescGrupo()     Sets the current record's "descGrupo" value
 * @method Grupo               setTareas()        Sets the current record's "Tareas" collection
 * @method Grupo               setGrupoUsuario()  Sets the current record's "Grupo_Usuario" collection
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrupo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grupo');
        $this->hasColumn('idGrupo', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombreGrupo', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('descGrupo', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tarea as Tareas', array(
             'local' => 'idGrupo',
             'foreign' => 'grupo_idGrupo'));

        $this->hasMany('Grupo_Usuario', array(
             'local' => 'idGrupo',
             'foreign' => 'grupo_idGrupo'));
    }
}