<?php

/**
 * BaseOtraTabla
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idOtra
 * @property string $nombreOtra
 * 
 * @method integer   getIdOtra()     Returns the current record's "idOtra" value
 * @method string    getNombreOtra() Returns the current record's "nombreOtra" value
 * @method OtraTabla setIdOtra()     Sets the current record's "idOtra" value
 * @method OtraTabla setNombreOtra() Sets the current record's "nombreOtra" value
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOtraTabla extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('otra_tabla');
        $this->hasColumn('idOtra', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('nombreOtra', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}