<?php

/**
 * BaseUsuario_Tarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario
 * @property integer $tarea
 * @property Usuario $Usuario
 * @property Tarea $Tarea
 * 
 * @method integer       getUsuario() Returns the current record's "usuario" value
 * @method integer       getTarea()   Returns the current record's "tarea" value
 * @method Usuario       getUsuario() Returns the current record's "Usuario" value
 * @method Tarea         getTarea()   Returns the current record's "Tarea" value
 * @method Usuario_Tarea setUsuario() Sets the current record's "usuario" value
 * @method Usuario_Tarea setTarea()   Sets the current record's "tarea" value
 * @method Usuario_Tarea setUsuario() Sets the current record's "Usuario" value
 * @method Usuario_Tarea setTarea()   Sets the current record's "Tarea" value
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario_Tarea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario__tarea');
        $this->hasColumn('usuario', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tarea', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'usuario',
             'foreign' => 'idUsuario',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Tarea', array(
             'local' => 'tarea',
             'foreign' => 'idTarea',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'fecha_asignacion',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'name' => 'fecha_actualizacion',
              'type' => 'timestamp',
             ),
             ));
        $this->actAs($timestampable0);
    }
}