<?php

/**
 * BaseUsuario_Tarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property integer $tarea_id
 * @property Usuario $Usuario
 * @property Tarea $Tarea
 * 
 * @method integer       getUsuarioId()  Returns the current record's "usuario_id" value
 * @method integer       getTareaId()    Returns the current record's "tarea_id" value
 * @method Usuario       getUsuario()    Returns the current record's "Usuario" value
 * @method Tarea         getTarea()      Returns the current record's "Tarea" value
 * @method Usuario_Tarea setUsuarioId()  Sets the current record's "usuario_id" value
 * @method Usuario_Tarea setTareaId()    Sets the current record's "tarea_id" value
 * @method Usuario_Tarea setUsuario()    Sets the current record's "Usuario" value
 * @method Usuario_Tarea setTarea()      Sets the current record's "Tarea" value
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario_Tarea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario__tarea');
        $this->hasColumn('usuario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tarea_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Tarea', array(
             'local' => 'tarea_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}