<?php

/**
 * BaseLugar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idLugar
 * @property string $tituloLugar
 * @property string $infoLugar
 * @property integer $mapaFK
 * @property Mapa $Mapa
 * 
 * @method integer getIdLugar()     Returns the current record's "idLugar" value
 * @method string  getTituloLugar() Returns the current record's "tituloLugar" value
 * @method string  getInfoLugar()   Returns the current record's "infoLugar" value
 * @method integer getMapaFK()      Returns the current record's "mapaFK" value
 * @method Mapa    getMapa()        Returns the current record's "Mapa" value
 * @method Lugar   setIdLugar()     Sets the current record's "idLugar" value
 * @method Lugar   setTituloLugar() Sets the current record's "tituloLugar" value
 * @method Lugar   setInfoLugar()   Sets the current record's "infoLugar" value
 * @method Lugar   setMapaFK()      Sets the current record's "mapaFK" value
 * @method Lugar   setMapa()        Sets the current record's "Mapa" value
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLugar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lugar');
        $this->hasColumn('idLugar', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('tituloLugar', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('infoLugar', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('mapaFK', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mapa', array(
             'local' => 'mapaFK',
             'foreign' => 'idMapa',
             'onDelete' => 'CASCADE'));
    }
}