<?php

/**
 * BaseProyectoUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idUsuario
 * @property integer $idProyecto
 * 
 * @method integer         getIdUsuario()  Returns the current record's "idUsuario" value
 * @method integer         getIdProyecto() Returns the current record's "idProyecto" value
 * @method ProyectoUsuario setIdUsuario()  Sets the current record's "idUsuario" value
 * @method ProyectoUsuario setIdProyecto() Sets the current record's "idProyecto" value
 * @property  $
 * @property  $
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProyectoUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proyecto_usuario');
        $this->hasColumn('idUsuario', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('idProyecto', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('usuario', array(
             'local' => 'idUsuario',
             'foreign' => 'idUsuario',
             'onDelete' => 'CASCADE'));

        $this->hasOne('proyecto', array(
             'local' => 'idProyecto',
             'foreign' => 'idProyecto',
             'onDelete' => 'CASCADE'));
    }
}