<?php

/**
 * BaseMapa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idMapa
 * @property string $nombreMapa
 * @property string $descMapa
 * @property integer $proyectoFK
 * @property Proyecto $Proyecto
 * @property Doctrine_Collection $Lugares
 * 
 * @method integer             getIdMapa()     Returns the current record's "idMapa" value
 * @method string              getNombreMapa() Returns the current record's "nombreMapa" value
 * @method string              getDescMapa()   Returns the current record's "descMapa" value
 * @method integer             getProyectoFK() Returns the current record's "proyectoFK" value
 * @method Proyecto            getProyecto()   Returns the current record's "Proyecto" value
 * @method Doctrine_Collection getLugares()    Returns the current record's "Lugares" collection
 * @method Mapa                setIdMapa()     Sets the current record's "idMapa" value
 * @method Mapa                setNombreMapa() Sets the current record's "nombreMapa" value
 * @method Mapa                setDescMapa()   Sets the current record's "descMapa" value
 * @method Mapa                setProyectoFK() Sets the current record's "proyectoFK" value
 * @method Mapa                setProyecto()   Sets the current record's "Proyecto" value
 * @method Mapa                setLugares()    Sets the current record's "Lugares" collection
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMapa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mapa');
        $this->hasColumn('idMapa', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombreMapa', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descMapa', 'string', 4000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 4000,
             ));
        $this->hasColumn('proyectoFK', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proyecto', array(
             'local' => 'proyectoFK',
             'foreign' => 'idProyecto',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Lugar as Lugares', array(
             'local' => 'idMapa',
             'foreign' => 'mapaFK'));
    }
}