<?php

/**
 * BaseRelacion_Tarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idRelacionTarea
 * @property integer $tareaOrigen
 * @property integer $tareaDestino
 * @property integer $relacion_idRelacion
 * @property Tarea $Tarea
 * @property Relacion $Relacion
 * 
 * @method integer        getIdRelacionTarea()     Returns the current record's "idRelacionTarea" value
 * @method integer        getTareaOrigen()         Returns the current record's "tareaOrigen" value
 * @method integer        getTareaDestino()        Returns the current record's "tareaDestino" value
 * @method integer        getRelacionIdRelacion()  Returns the current record's "relacion_idRelacion" value
 * @method Tarea          getTarea()               Returns the current record's "Tarea" value
 * @method Relacion       getRelacion()            Returns the current record's "Relacion" value
 * @method Relacion_Tarea setIdRelacionTarea()     Sets the current record's "idRelacionTarea" value
 * @method Relacion_Tarea setTareaOrigen()         Sets the current record's "tareaOrigen" value
 * @method Relacion_Tarea setTareaDestino()        Sets the current record's "tareaDestino" value
 * @method Relacion_Tarea setRelacionIdRelacion()  Sets the current record's "relacion_idRelacion" value
 * @method Relacion_Tarea setTarea()               Sets the current record's "Tarea" value
 * @method Relacion_Tarea setRelacion()            Sets the current record's "Relacion" value
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRelacion_Tarea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('relacion__tarea');
        $this->hasColumn('idRelacionTarea', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('tareaOrigen', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tareaDestino', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('relacion_idRelacion', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tarea', array(
             'local' => 'tareaDestino',
             'foreign' => 'idTarea',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Relacion', array(
             'local' => 'relacion_idRelacion',
             'foreign' => 'idRelacion',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'fecha_creacion',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'name' => 'fecha_actualizacion',
              'type' => 'timestamp',
             ),
             ));
        $this->actAs($timestampable0);
    }
}