<?php

/**
 * BaseStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idStatus
 * @property string $nombreStatus
 * @property Doctrine_Collection $Proyectos
 * @property Doctrine_Collection $Tareas
 * @property Doctrine_Collection $RegistroEstados
 * 
 * @method integer             getIdStatus()        Returns the current record's "idStatus" value
 * @method string              getNombreStatus()    Returns the current record's "nombreStatus" value
 * @method Doctrine_Collection getProyectos()       Returns the current record's "Proyectos" collection
 * @method Doctrine_Collection getTareas()          Returns the current record's "Tareas" collection
 * @method Doctrine_Collection getRegistroEstados() Returns the current record's "RegistroEstados" collection
 * @method Status              setIdStatus()        Sets the current record's "idStatus" value
 * @method Status              setNombreStatus()    Sets the current record's "nombreStatus" value
 * @method Status              setProyectos()       Sets the current record's "Proyectos" collection
 * @method Status              setTareas()          Sets the current record's "Tareas" collection
 * @method Status              setRegistroEstados() Sets the current record's "RegistroEstados" collection
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('status');
        $this->hasColumn('idStatus', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombreStatus', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Proyecto as Proyectos', array(
             'local' => 'idStatus',
             'foreign' => 'statusPK'));

        $this->hasMany('Tarea as Tareas', array(
             'local' => 'idStatus',
             'foreign' => 'statusPK'));

        $this->hasMany('Registro_Estado_Tarea as RegistroEstados', array(
             'local' => 'idStatus',
             'foreign' => 'statusPK'));
    }
}