<?php

/**
 * BaseTema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idTema
 * @property string $tituloTema
 * @property integer $proyectoFK
 * @property integer $usuarioFK
 * @property Proyecto $Proyecto
 * @property Usuario $Usuario
 * @property Doctrine_Collection $Temas
 * 
 * @method integer             getIdTema()     Returns the current record's "idTema" value
 * @method string              getTituloTema() Returns the current record's "tituloTema" value
 * @method integer             getProyectoFK() Returns the current record's "proyectoFK" value
 * @method integer             getUsuarioFK()  Returns the current record's "usuarioFK" value
 * @method Proyecto            getProyecto()   Returns the current record's "Proyecto" value
 * @method Usuario             getUsuario()    Returns the current record's "Usuario" value
 * @method Doctrine_Collection getTemas()      Returns the current record's "Temas" collection
 * @method Tema                setIdTema()     Sets the current record's "idTema" value
 * @method Tema                setTituloTema() Sets the current record's "tituloTema" value
 * @method Tema                setProyectoFK() Sets the current record's "proyectoFK" value
 * @method Tema                setUsuarioFK()  Sets the current record's "usuarioFK" value
 * @method Tema                setProyecto()   Sets the current record's "Proyecto" value
 * @method Tema                setUsuario()    Sets the current record's "Usuario" value
 * @method Tema                setTemas()      Sets the current record's "Temas" collection
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTema extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tema');
        $this->hasColumn('idTema', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('tituloTema', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('proyectoFK', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('usuarioFK', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proyecto', array(
             'local' => 'proyectoFK',
             'foreign' => 'idProyecto',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Usuario', array(
             'local' => 'usuarioFK',
             'foreign' => 'idUsuario',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Comentario as Temas', array(
             'local' => 'idTema',
             'foreign' => 'temaFK'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'fecha_creacion',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'name' => 'fecha_actualizacion',
              'type' => 'timestamp',
             ),
             ));
        $this->actAs($timestampable0);
    }
}