<?php

/**
 * BaseRelacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombreRelaion
 * @property Doctrine_Collection $Relacion_Tarea
 * 
 * @method string              getNombreRelaion()  Returns the current record's "nombreRelaion" value
 * @method Doctrine_Collection getRelacionTarea()  Returns the current record's "Relacion_Tarea" collection
 * @method Relacion            setNombreRelaion()  Sets the current record's "nombreRelaion" value
 * @method Relacion            setRelacionTarea()  Sets the current record's "Relacion_Tarea" collection
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRelacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('relacion');
        $this->hasColumn('nombreRelaion', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Relacion_Tarea', array(
             'local' => 'id',
             'foreign' => 'relacion_idRelacion'));
    }
}