<?php

/**
 * BaseComentario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idComentario
 * @property string $contenidoComentario
 * @property integer $usuarioFK
 * @property integer $temaFK
 * @property Usuario $Usuario
 * @property Tema $Tema
 * 
 * @method integer    getIdComentario()        Returns the current record's "idComentario" value
 * @method string     getContenidoComentario() Returns the current record's "contenidoComentario" value
 * @method integer    getUsuarioFK()           Returns the current record's "usuarioFK" value
 * @method integer    getTemaFK()              Returns the current record's "temaFK" value
 * @method Usuario    getUsuario()             Returns the current record's "Usuario" value
 * @method Tema       getTema()                Returns the current record's "Tema" value
 * @method Comentario setIdComentario()        Sets the current record's "idComentario" value
 * @method Comentario setContenidoComentario() Sets the current record's "contenidoComentario" value
 * @method Comentario setUsuarioFK()           Sets the current record's "usuarioFK" value
 * @method Comentario setTemaFK()              Sets the current record's "temaFK" value
 * @method Comentario setUsuario()             Sets the current record's "Usuario" value
 * @method Comentario setTema()                Sets the current record's "Tema" value
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComentario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comentario');
        $this->hasColumn('idComentario', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('contenidoComentario', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('usuarioFK', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('temaFK', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'usuarioFK',
             'foreign' => 'idUsuario',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Tema', array(
             'local' => 'temaFK',
             'foreign' => 'idTema',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'fecha_creacion',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'name' => 'fecha_actualizacion',
              'type' => 'timestamp',
             ),
             'NestedSet' => 
             array(
              'hasManyRoots' => true,
              'rootColumnName' => 'root_id',
             ),
             ));
        $this->actAs($timestampable0);
    }
}