<?php

/**
 * BaseRegistro_Estado_Tarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idRegistroTarea
 * @property timestamp $fecha_cambio_estado
 * @property integer $status_idStatus
 * @property integer $tarea_idTarea
 * @property Status $Status
 * @property Tarea $Tarea
 * 
 * @method integer               getIdRegistroTarea()     Returns the current record's "idRegistroTarea" value
 * @method timestamp             getFechaCambioEstado()   Returns the current record's "fecha_cambio_estado" value
 * @method integer               getStatusIdStatus()      Returns the current record's "status_idStatus" value
 * @method integer               getTareaIdTarea()        Returns the current record's "tarea_idTarea" value
 * @method Status                getStatus()              Returns the current record's "Status" value
 * @method Tarea                 getTarea()               Returns the current record's "Tarea" value
 * @method Registro_Estado_Tarea setIdRegistroTarea()     Sets the current record's "idRegistroTarea" value
 * @method Registro_Estado_Tarea setFechaCambioEstado()   Sets the current record's "fecha_cambio_estado" value
 * @method Registro_Estado_Tarea setStatusIdStatus()      Sets the current record's "status_idStatus" value
 * @method Registro_Estado_Tarea setTareaIdTarea()        Sets the current record's "tarea_idTarea" value
 * @method Registro_Estado_Tarea setStatus()              Sets the current record's "Status" value
 * @method Registro_Estado_Tarea setTarea()               Sets the current record's "Tarea" value
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistro_Estado_Tarea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registro__estado__tarea');
        $this->hasColumn('idRegistroTarea', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('fecha_cambio_estado', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('status_idStatus', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tarea_idTarea', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Status', array(
             'local' => 'status_idStatus',
             'foreign' => 'idStatus',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Tarea', array(
             'local' => 'tarea_idTarea',
             'foreign' => 'idTarea',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}