<?php

/**
 * BaseAvance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idAvance
 * @property string $tituloAvance
 * @property string $resumen
 * @property integer $duracion
 * @property timestamp $fechaInicio
 * @property timestamp $fechaFinal
 * @property integer $tareaFK
 * @property Tarea $Tarea
 * 
 * @method integer   getIdAvance()     Returns the current record's "idAvance" value
 * @method string    getTituloAvance() Returns the current record's "tituloAvance" value
 * @method string    getResumen()      Returns the current record's "resumen" value
 * @method integer   getDuracion()     Returns the current record's "duracion" value
 * @method timestamp getFechaInicio()  Returns the current record's "fechaInicio" value
 * @method timestamp getFechaFinal()   Returns the current record's "fechaFinal" value
 * @method integer   getTareaFK()      Returns the current record's "tareaFK" value
 * @method Tarea     getTarea()        Returns the current record's "Tarea" value
 * @method Avance    setIdAvance()     Sets the current record's "idAvance" value
 * @method Avance    setTituloAvance() Sets the current record's "tituloAvance" value
 * @method Avance    setResumen()      Sets the current record's "resumen" value
 * @method Avance    setDuracion()     Sets the current record's "duracion" value
 * @method Avance    setFechaInicio()  Sets the current record's "fechaInicio" value
 * @method Avance    setFechaFinal()   Sets the current record's "fechaFinal" value
 * @method Avance    setTareaFK()      Sets the current record's "tareaFK" value
 * @method Avance    setTarea()        Sets the current record's "Tarea" value
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAvance extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('avance');
        $this->hasColumn('idAvance', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('tituloAvance', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('resumen', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('duracion', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('fechaInicio', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('fechaFinal', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('tareaFK', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tarea', array(
             'local' => 'tareaFK',
             'foreign' => 'idTarea',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'fechaCreacion',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'name' => 'fechaActulizacion',
              'type' => 'timestamp',
             ),
             ));
        $this->actAs($timestampable0);
    }
}