

status:
  class: sfDoctrineRouteCollection
  options:
    model:                Status
    module:               status
    prefix_path:          /status
    column:               idStatus
    with_wildcard_routes: true

prioridad:
  class: sfDoctrineRouteCollection
  options:
    model:                Prioridad
    module:               prioridad
    prefix_path:          /prioridad
    column:               idPrioridad
    with_wildcard_routes: true

usuario:
  class: sfDoctrineRouteCollection
  options:
    model:                Usuario
    module:               usuario
    prefix_path:          /usuario
    column:               idUsuario
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: usuario, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
