<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/08/18 22:10:19

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=gproject',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
