<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/07/01 17:02:07

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=gproject',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
