<?php

/**
 * AvanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AvanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AvanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Avance');
    }
    
    public function getAvancesByTarea($idTarea){
     $avances  = Doctrine_Query::create()
                ->from('Avance a')
                ->where('a.tareaFK',$idTarea)
                ->execute() ;             
      

          return $avances;
   }
        
    
}
