<?php

/**
 * EventoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventoTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object EventoTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Evento');
    }

    public function getEventosByUsuario($idUsuario = 1) {

        $proyectos = Doctrine_Core::getTable('Proyecto')->getProyectoByUsuario($idUsuario);


        $query = Doctrine_Query::create()
                ->select('e.fechaEvento')
                ->from('Evento e')
                ->whereIn('e.proyectoFK=?', $proyectos);

        return $query->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)->execute();
    }

    public function getEventosByProyecto($idProyecto) {

        $custom_logger = new sfFileLogger(new sfEventDispatcher(), array('file' => sfConfig::get('sf_log_dir') . '/optional.log'));

        $custom_logger->notice("buscadno eventos de proyecto " . $idProyecto);


        $eventos = $this->createQuery('a')
                ->where("proyectofk = ?", $idProyecto)
                ->execute();

        return $eventos;


        }

        
        
        
   public function getEventosByProyectoAndRango($idProyecto,$fechaInicial,$fechaFinal) {
 $custom_logger = new sfFileLogger(new sfEventDispatcher(), array('file' => sfConfig::get('sf_log_dir') . '/optional.log'));

        $custom_logger->notice("inicio en rago es  " . $fechaInicial);

 


        $eventos = $this->createQuery('e')
                ->where("e.proyectofk = ?", $idProyecto)
                ->andWhere("e.fechaInicio >= ?", $fechaInicial)
                ->andWhere("e.fechaFinal <= ?", $fechaFinal) 
                ->execute();

        return $eventos;


        }
        
      

}