<?php

/**
 * EventoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Evento');
    }
}