<?php

/**
 * Grupo_UsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Grupo_UsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Grupo_UsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Grupo_Usuario');
    }
}