<?php

/**
 * LugarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LugarTable extends sfMapFishTable
{
    
   public static $geometryColumn = array('geo_info' => 4326);  


  /**
     * Returns an instance of this class.
     *
     * @return object LugarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Lugar');
    }
}
