<?php

/**
 * MapaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MapaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MapaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mapa');
    }
}