<?php

/**
 * OtraTablaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OtraTablaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OtraTablaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OtraTabla');
    }
}