<?php

/**
 * PerfilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PerfilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PerfilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Perfil');
    }
    
    
     public function getNombrePerfil($idPerfil){
        $query = Doctrine_Query::create()
          ->from('Perfil p')
          ->where('idPerfil = ?', $idPerfil);
          
       return $query->execute()->getFirst();  
   
    }
}