<?php

/**
 * PrioridadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrioridadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrioridadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Prioridad');
    }
}