<?php

/**
 * ProyectoUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProyectoUsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProyectoUsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProyectoUsuario');
    }
    
   
    
}