<?php

/**
 * ProyectoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProyectoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProyectoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Proyecto');
    }
    
    public function getProyectos(){
        
       return   Doctrine_Query::create()
           ->select('p.*, s.nombreStatus, p.nombrePrioridad' )
           ->from('Proyecto p, p.statusFK s, p.prioridadFK p')
           ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)->execute();         
                
    }
    
    public function getProyectoByUsuario($idUsuario){
        
        $query =  $this->getQueryProyectoPorUsuario($idUsuario);
        return  $query->execute();     
               
        
    }
    

     public function getQueryProyectoPorUsuario($idUsuario) {
             $query =    Doctrine_Query::create()
                ->from('Proyecto p')
                ->leftJoin('p.Usuario us')
               // ->innerJoin('us.usuario u')
                ->where('us.idUsuario=?',$idUsuario);
                
             
             return $query;
    }

    
    private function getQueryProyectoByUsuario($idUsuario){
        
          $query = Doctrine_Query::create()
                ->from('Proyecto p')
                ->leftJoin('ProyectoUsuario usuario')
                ->where('u.idUsuario=?',$idUsuario)
                ->andWhere('p.idProyecto =  u.idProyecto');
          
          return $query;
    }
    
    
    public function getProyectoById($idProyecto){
        
         $query = Doctrine_Query::create('p')
                  ->where('p.idproyecto = ?' , $idProyecto)
                  ->execute();
                
          return $query;
        
    }
    
    
    
     public function getProyectoPorPrioridad($prioridadId ) {
        $query = Doctrine_Query::create()
                ->from('Proyecto p')
                ->where("p.statusPK = ?", $prioridadId);
        
        return $query->execute();
    }
    
     
    
}