<?php

/**
 * Registro_Estado_TareaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Registro_Estado_TareaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Registro_Estado_TareaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Registro_Estado_Tarea');
    }
}