<?php

/**
 * Relacion_TareaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Relacion_TareaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Relacion_TareaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Relacion_Tarea');
    }
}