<?php

/**
 * TareaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TareaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TareaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tarea');
    }
}