<?php

/**
 * Tarea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tarea extends BaseTarea
{

    public function __toString(){
        
      return  $this->getNombreTarea();
    }
    
    
    public function getId(){

        return $this->getIdTarea();
    }
    
}
