<?php

/**
 * Tipo_usuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Tipo_usuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Tipo_usuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipo_usuario');
    }
}