<?php

/**
 * UsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Usuario');
    }
    
    
       
    public function existeUsuario($nombreUsuario , $password){
        
        $q = Doctrine_Query::create()
          ->select('u.* , p.perfilNombre')      
          ->from('Usuario u')
          ->leftJoin('u.Perfil p') 
          ->where('u.usr_nick = ?', $nombreUsuario)
          ->andWhere('u.password = ?', $password);
             
          return $q->execute()->getFirst();
    
        
        }
        
}