<?php

/**
 * Usuario_TareaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Usuario_TareaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Usuario_TareaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Usuario_Tarea');
    }
}