<?php

/**
 * UsuarioTareaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioTareaTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioTareaTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('UsuarioTarea');
    }

    public function getArbolTareasByUsuario($idUsuario) {
       
       $listaTareas = $this->getTareasByUsuario($idUsuario); 
        
      
        return TareaTable::getInstance()
                ->getArbolCojuntoTareas($listaTareas);
    }

    public function getTareasByUsuario($idUsuario) {

       
        $lstTareas = Doctrine_Query::create()
                ->select('ut.*')
                ->from('UsuarioTarea ut')
                ->leftJoin('ut.idTarea')
                ->where('ut.idUsuario = ?', $idUsuario)
                ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
                ->execute();

        return $lstTareas;
    }

}