# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css,menu_style.css,redmond/jquery-ui-1.8.23.custom.css,gh-buttons.css,double_list_widget_style.css,,customJqueryUI.css]

  javascripts:    [jquery-1.7.2.js,jquery-ui-1.8.21.min.js,double_list.js,inicializacionGeneral.js, customStyleSelect.js, jquery.form.js ,OpenLayers.js ]

  has_layout:     true
  layout:         layout
