generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Proyecto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          proyecto_proyecto
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
          title: Administración de proyectos 
      filter:  ~
      form:    ~
      edit:    
         title: Edición Proyecto "%%nombre_proyecto%%%"
      new:     ~
