<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/09/02 20:26:38

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet_test',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
