# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Login
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css,login.css,menu_style.css,login/animate.css,login/reset.css,login/styles.css,gh-buttons.css]
  javascripts:    [jquery-1.7.2.js]

  has_layout:     true 
  layout:         layout_login
