<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/12/18 05:43:45

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=gproject',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
