<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/11/27 08:28:29
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'gerente',
        1 => 'ejecutor',
      ),
    ),
  ),
);
