<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/12/09 22:25:43
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'gerente',
        1 => 'ejecutor',
      ),
    ),
  ),
);
